<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vfb-3</name>
   <tag></tag>
   <elementGuidId>b3075d6e-4d32-4ad5-8342-59f9986cd2b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f16c276-e376-4da5-9c8a-16db6f415ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfa711ff-f70d-48ee-955c-a802efee3406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-3</value>
      <webElementGuid>2cc891fb-833e-4ac9-a176-ef613f7b6449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-3</value>
      <webElementGuid>f4ecba2c-7039-49ca-8b28-cd0ff35914de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium  required {digits:true,maxlength:2,minlength:2} </value>
      <webElementGuid>7bd244d1-b0d5-4883-92bd-10c449b503c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-3&quot;)</value>
      <webElementGuid>e31b8ec2-fcb6-4f61-b05c-13df057ab2fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-3']</value>
      <webElementGuid>62ea6ad7-fee5-4280-a08f-102a845f09c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='item-vfb-2']/ul/li/span/input</value>
      <webElementGuid>9fb5f6ec-0218-4a13-9b09-2a5223e392f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/ul/li/span/input</value>
      <webElementGuid>3d9939fa-3310-404b-b8a8-de00c8f4efa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-3' and @id = 'vfb-3']</value>
      <webElementGuid>02829cd4-1e72-45b0-837e-6557c6793007</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
