<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>city</name>
   <tag></tag>
   <elementGuidId>d389539a-c094-4aca-9b19-e98bf6141465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-13-zip']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-13-zip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>645157ac-9cb4-4179-991a-0c39b430d0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>180fa2b7-fc5a-4570-82fd-6a001614a951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-13[zip]</value>
      <webElementGuid>41e21c8a-7109-4242-92c1-7727bee1ca0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-13-zip</value>
      <webElementGuid>c5c24fd0-2059-46e2-b127-a1b4435f2a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>dd2e9a9d-a750-44dd-a0f6-23b328d1f104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text vfb-medium  </value>
      <webElementGuid>cffbe013-970a-49b2-908e-6de5075b42e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-13-zip&quot;)</value>
      <webElementGuid>f0fee5b9-9f1e-4a1d-9e63-a8a15a89730a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-13-zip']</value>
      <webElementGuid>bbf40c06-8574-45b3-9914-11bf1add5127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-13']/div/span[5]/input</value>
      <webElementGuid>67752cc4-615c-46ac-a9e9-18685efa51a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/input</value>
      <webElementGuid>4db6f1df-5d2c-4433-abd5-1d60f7d721db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-13[zip]' and @id = 'vfb-13-zip']</value>
      <webElementGuid>9facab0c-bf9a-49c6-90b6-f611d337e425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
